# Generated by Django 6.0.5 on 2026-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerNotification',
            fields=[
                ('crn_container_no', models.CharField(db_column='CRN_CONTAINER_NO', max_length=30, primary_key=True, serialize=False)),
                ('crn_status', models.IntegerField(db_column='CRN_STATUS', default=0)),
            ],
            options={
                'db_table': 'CNT_RECVD_NOTIFICATION',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
